---
# [Interface]
# PrivateKey = asdf=

# [Peer]
# PublicKey = asdf=
# Endpoint = 1.2.3.4:51820
# AllowedIPs = 0.0.0.0/0
# PersistentKeepalive = 25
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wireguard-config
  namespace: qbt
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    wg0.conf: AgBatPGrJmR5zOUQGcRc/TyzBcJfiybg3/Q4VVsXBqEhS4hZ/iu/xN8DODGo4C8Shh3K7oCLyHQfzoeiRCSgglxdSNiAU2lsyIDaLb4cAK7xNnTlFXZRUZT1Q6BGXbujH81ChTxzc3qJo3GWobcNkgSoPtzxSqBkrSbyENHXkZQHb+UlTzCLlA5vqnTRjkj/VHu1qFWmnR6mz7SeolB8BXGVd0mGaAgbW7ICy0BtOGC7rBvzBcAh2UhNVoFC73WsA83laI0j/UZf2sZ3bn1ziE3WI0edBpwTSJTTonsmIMlf8+brQdf+/bJq/oFFkugk3GA/yWWo0YcLhWvQ+0VRFqq3ssP3QpRvmI770W8OAMRHGldn8W98E9DWrnxmnHuTLjriRvrVU1xO2HyJbb0d8Iq02yEhJouQrDYbRv+eSmX8FqXJwXQP0tS+7vwcYztyMpXD5zCOi7DDsNnCN2EuoCoILSD9SPbNucJR7cCLv9Vx+UhRA3yxncpN5CNlnh1UXXdtN2+IrThyL9cuOaZM7MmAsMxxo4CmcdMHWWo5joqimowvSWoetUZHW+Gnb6O5hu2zPe4Gg0lpnfWp+EkdDgVwxqieKo6UTlkl7aXdrJ4BtF99WaCvuOuty90nCrMiEsvfkUzDMWuJAATlDE9g6DzufOjp9mUjl7ebS0I450c+ZBTHsTD25s05BuR6KkWQZvyEgGNg0v+9ztAuwiUigaZAqNe1tOatrBjvfvA4amaBM7bgjbb/7gAbA8lA0sqxt3Jr+NoxOfh/KCuhMlwyCbFqD9Kzk3ceW7oFvNak75qWY9larmVGjlHfXtYaSHNWMACJaLBon36oC6lYjrPCfYlnqXCzUjaDLBpOJ95a9IMdeaOtkYLk0Hov92zQ1DiyVCO1lSyss+TazEIfH9jZV7ir9becSR/FpcZERsQdjTc/H6j/jgl46zoGmr9/GFO42qwCwYxK0ns2DN53fS1naf/zKwwc/sI=
  template:
    metadata:
      name: wireguard-config
      namespace: qbt
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
    type: Opaque
